### ISSUE TITLE
XP bar positioning too high on player screen

### ISSUE THREAD

**Issue by carlroberts99** [the-playground/xpsys-but-not-disabled#4]
![bar](https://user-images.githubusercontent.com/48777329/57527396-72e46400-7327-11e9-8fe1-904a4af685aa.png)

See attached screenshot, maybe put the bar towards the top of the screen now the news ticker is removed? @Etothepowerof26

**Comment by Etothepowerof26** [comment]
I'll do it when I get home

**Comment by carlroberts99** [comment]
Sure thing, while you're at it, caught the error with the hook:

xp update hook failed, something went wrong!
addons/xpsys/lua/xpsys/sv_leveling.lua:26: attempt to call method 'GetExperience' (a nil value)

**Comment by carlroberts99** [comment]
Extra error addons/xpsys/lua/xpsys/sv_leveling.lua:55: attempt to call method 'ChatPrintColor' (a nil value)
  1. fn - addons/xpsys/lua/xpsys/sv_leveling.lua:55
   2. unknown - addons/ulib/lua/ulib/shared/hook.lua:109

**Comment by Etothepowerof26** [comment]
ok, so it's a loading issue. I'll separate this into 2 separate issues
